services:
  blog-service:
    build: ./Microservices/blog-service
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal  # Make sure this matches the GitHub Actions PostgreSQL service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=Coursework
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret

  mf-blog:
    build: ./Microfrontends/mf-blog
    ports:
      - "3000:3000"

  country-service:
    build: ./Microservices/country-service
    ports:
      - "7000:7000"
